# Generated by Django 4.2.7 on 2023-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
