# Generated by Django 4.2.7 on 2023-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_roomprivate_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
