# Generated by Django 4.2.7 on 2023-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomprivate_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprivate',
            name='is_creator',
            field=models.BooleanField(default=True),
        ),
    ]
