# Generated by Django 4.2.7 on 2023-12-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover pics'),
        ),
    ]
