# Generated by Django 4.2.7 on 2023-12-25 13:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_playlist_name_alter_roomprivate_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=main.models.RoomCode, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
