# Generated by Django 4.2.7 on 2023-12-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_access_token_user_expires_in_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
