# Generated by Django 4.2.7 on 2023-12-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_roomprivate_created_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpublic',
            name='room',
        ),
        migrations.RemoveField(
            model_name='commentpublic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='roompublic',
            name='current_playlist',
        ),
        migrations.RemoveField(
            model_name='roompublic',
            name='playlist_1',
        ),
        migrations.RemoveField(
            model_name='roompublic',
            name='playlist_2',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='song',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentPrivate',
        ),
        migrations.DeleteModel(
            name='CommentPublic',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
        migrations.DeleteModel(
            name='RoomPublic',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
